# Generated by Django 5.2.6 on 2025-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='contacts', to='contact_app.tag'),
        ),
    ]
