# Generated by Django 5.2.6 on 2025-09-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_alter_contact_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
